[package]
name = "sable"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossbeam = "0.8.4"
pixels = "0.13.0"
rand = "0.8.5"
softbuffer = "0.4.2"
winit = { version = "0.29", features = ["rwh_05"] }
