[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
error-iter = "0.4.1"
log = "0.4.21"
pixels = "0.13.0"
rand = "0.8.5"
softbuffer = "0.4.2"
winit = { version = "0.29", features = ["rwh_05"] }
